import Head from 'next/head'
import { Navbar } from '../components/navbar'
import { Swiper, SwiperSlide } from 'swiper/react';

export default function Home() {
  return (
    <div>
      <Head>
        <title>cake corner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main >
        <div className='min-h-screen  bg-cover bg-[url("/images/pexels-carlie-wright-6346166.jpg")]'>
          <div className='min-h-screen flex justify-center mx-auto px-16 gap-10  text-center h-full bg-gradient-to-b from-gray-600/60 to-gray-200/40'>

            <div className=' items-center flex flex-col justify-center my-auto h-full order-first gap-10 mx-20 '>
              <h1 className='text-black text-6xl  mt-auto font-black'>
                Well being of our clients first!
              </h1>
              <a href="#test" className='mt-auto bg-[#425c4e] mx-auto px-6 py-4 rounded-xl text-white font-medium hover:bg-[#978f83] transition duration-300'>Explore Us</a>
            </div>
          </div>
        </div>
        <div id='test' className=' bg-gray-50 text-center scroll-mt-20 py-20 space-y-5'>
          <h1 className='text-5xl'>clients choose us</h1>
          <h2 className='text-xl text-gray-600'>Discover The Art Of Sweetness ,Choose Your Favorite Product</h2>
          <div className='grid md:grid-cols-4 gap-10 px-20 !mt-20'>
            <div className='circle bg-orange-200'>
              <img className='w-20' src='images/pngable_dessert-icon-desserts-and-candies-icon-pudding-icon.png'></img>
            </div>
            <div className='bg-sky-200 circle'>
              <img className='w-20' src='images/transparent-gastronomy-icon-muffin-icon-cupcake-icon-5f946322a295c1.878142701603560226666.png'></img>
            </div>
            <div className='bg-fuchsia-200 circle'>
              <img className='w-20' src='images/transparent-dessert-and-candies-icon-cheesecake-icon-cake-icon-604a8785cce064.5668002616154970938392.png'></img>
            </div>
            <div className='bg-purple-300 circle'>
              <img className='w-20' src='images/transparent-wedding-cake-icon-cake-icon-family-icon-5f628d45c49311.5451545216002942138052.png'></img>
            </div>
          </div>
        </div>
        {/* testimonials */}
        <div className='bg-[rgb(208,224,216)]'>
          <div className='container mx-auto px-16 gap-10  grid grid-cols-2'>
            {/* col1 */}
            <div className='py-20'>
              <h1 className=' text-5xl capitalize mb-10' >our work is dedicated to the prosperity of our clients!</h1>
              <p className='opacity-75'>Since 1993 cake corner has provided Brooklyn, Bushwick, and the rest of the country with the best in Wedding Cakes, Birthday Cakes Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita similique quod illum velit sed alias numquam reprehenderit nemo eveniet quae eum vel, aliquam excepturi ea, assumenda possimus praesentium amet est.</p>
            </div>
            {/* col2 */}
            <div className='bg-[rgb(173,204,188)]'>
              <Swiper
                spaceBetween={50}
                slidesPerView={1}
              >
                <SwiperSlide className=''></SwiperSlide>

              </Swiper>



            </div>
          </div>
        </div>



      </main>

    </div>
  )
}
