import Head from 'next/head';
import { useRef } from 'react';
import { FiArrowLeft, FiArrowRight } from 'react-icons/fi';
import SwiperCore, { Autoplay, Navigation } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import Circle from '../components/circle';
import { Navbar } from '../components/navbar';
import Product from '../components/Product';
import ToTopButton from '../components/ToTopButton';
SwiperCore.use([Autoplay, Navigation])


export default function Home() {
  const testNavLeft = useRef(null)
  const testNavRight = useRef(null)



  return (
    <div>
      <Head>
        <title>cake corner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <ToTopButton />

      <main >
        <div className='min-h-screen  bg-cover bg-[url("/images/pexels-carlie-wright-6346166.jpg")]'>
          <div className='min-h-screen flex justify-center mx-auto px-16 gap-10  text-center h-full bg-gradient-to-b from-[#2e2e2e79] to-[#4949495d]'>

            <div className=' items-center flex flex-col justify-center my-auto h-full order-first gap-10 mx-20 '>
              <h1 className='text-white text-6xl lobster mt-auto font-black '>
                Well being of our clients first!
              </h1>
              {/* button */}
              <a href=' ' className={' p-2 relative  overflow-hidden group text-sm'}>
                <span className=" absolute text-md bg-[#050505]  inset-x-0 h-[2px] bottom-0 group-hover:opacity-100 translate-x-full ml-20 group-hover:ml-0 group-hover:translate-x-0 transition-all duration-300"> </span>
                <span className="relative font-medium text-xl">Explore us</span>
              </a>
            </div>
          </div>
        </div>
        {/* products */}
        <div id='test' className='  text-center scroll-mt-20 py-20 space-y-5'>
          <h1 className='text-5xl'>clients choose us</h1>
          <h2 className='text-xl text-gray-600'>Discover The Art Of Sweetness ,Choose Your Favorite Product</h2>
          <div className='grid md:grid-cols-4 gap-10 px-20 !mt-20'>
            <Circle color="bg-color1" imgSrc={"images/transparent-wedding-cake-icon-cake-icon-family-icon-5f628d45c49311.5451545216002942138052.png"}  name={'cakes'} />
            <Circle color={"bg-color2"} imgSrc={'images/transparent-gastronomy-icon-muffin-icon-cupcake-icon-5f946322a295c1.878142701603560226666.png'}  name={'cupcakes'} />
            <Circle color={"bg-color3"} imgSrc={'images/transparent-dessert-and-candies-icon-cheesecake-icon-cake-icon-604a8785cce064.5668002616154970938392.png'} name={'cheesecakes'} />
            <Circle color={"bg-color4"} imgSrc={'images/pngable_dessert-icon-desserts-and-candies-icon-pudding-icon.png'}  name={'desserts'} />


          </div>
        </div>

        {/* testimonials */}
        <div className='bg-[rgb(208,224,216)]'>
          <div className='container mx-auto px-16 gap-10  grid grid-cols-2'>
            {/* col1 */}
            <div className='py-20'>
              <h1 className=' text-5xl capitalize mb-10' >our work is dedicated to the prosperity of our clients!</h1>
              <p className='opacity-75'>Since 1993 cake corner has provided Brooklyn, Bushwick, and the rest of the country with the best in Wedding Cakes, Birthday Cakes Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita similique quod illum velit sed alias numquam reprehenderit nemo eveniet quae eum vel, aliquam excepturi ea, assumenda possimus praesentium amet est.</p>
            </div>
            {/* col2 */}
            <div className='bg-[rgb(173,204,188)] flex flex-col gap-5 py-20 px-10 overflow-hidden'>
              <h1 className='pacifico text-4xl  text-[#fff]'>Testimonials</h1>

              <img className='w-[60px]' src="images/transparent-review-icon-feedback-and-testimonials-icon-testimo-5dc8fc753daf66.5488601215734529172527.png" />
              <div className="flex justify-end gap-2 mb-4">
                <button ref={testNavLeft} className='disabled:bg-transparent disabled:opacity-50 text-[#fff] text-2xl p-1 rounded-full hover:bg-white/20'>
                  <FiArrowLeft />
                </button>
                <button ref={testNavRight} className='disabled:bg-transparent disabled:opacity-50 text-[#fff] text-2xl p-1 rounded-full hover:bg-white/20'>
                  <FiArrowRight />
                </button>
              </div>
              <Swiper className='h-full w-full'
                modules={[Autoplay]}
                autoplay={{
                  delay: 3000,
                }}
                loop
                spaceBetween={50}
                slidesPerView={1}
                onInit={(swiper) => {
                  swiper.params.navigation.prevEl = testNavLeft.current
                  swiper.params.navigation.nextEl = testNavRight.current
                  swiper.navigation.init()
                  swiper.navigation.update()
                }}
                navigation={{
                  prevEl: testNavLeft.current,
                  nextEl: testNavRight.current,
                }}

              >
                <SwiperSlide className='text-white text-4xl flex flex-col gap-10'>
                  <p>love your products, the quality has been incredible year after year.I tell everyone I know that they have to try cake corner</p>
                  <span>Bailey H.</span>
                </SwiperSlide>
                <SwiperSlide className='text-[#fff] text-4xl flex flex-col gap-10'>
                  <p>love your products, the quality has been incredible year after year.I tell everyone I know that they have to try cake corner</p>
                  <span>Bailey H.</span>
                </SwiperSlide>
                <SwiperSlide className='text-[#fff] text-4xl flex flex-col gap-10'>
                  <p>love your products, the quality has been incredible year after year.I tell everyone I know that they have to try cake corner</p>
                  <span>Bailey H.</span>
                </SwiperSlide>


              </Swiper>

            </div>
          </div>
        </div>

        {/* hot selling products */}
        <div className="container mx-auto text-center pt-20 max-w-screen-xl text-[#83a59d] capitalize">
          <h1 className='text-5xl'>hot selling products </h1>
        </div>
        <div className="grid grid-cols-4 container mx-auto py-20 max-w-screen-xl">
          <Product src="images/image/lemon-pound-cake.jpg" price={35} name={'lemon pound cake'} />
          <Product src={"images/image/pexels-kristina-paukshtite-1998633.jpg"} price={5} name={'mini chocolate'} />
          <Product src={"images/image/pexels-roman-odintsov-5897462.jpg"} price={6} name={'Raspberry Crumble Bar'} />
          <Product src={"images/image/pexels-amanda-lim-8774191.jpg"} price={40} name={'Chocolate Matcha Suiss Roll'} />
        </div>




      </main>

    </div>
  )
}
